---
apiVersion: v1
kind:       Service
metadata:
  name: dictionary
spec:
  type: NodePort
  selector:
    app: dictionary
  ports:
    - name:       http
      protocol:   TCP
      nodePort:   CHANGE_ME!
      port:       4000