kind:       Deployment
apiVersion: apps/v1
metadata:
  name: dictionary-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary
      rev: v1
  template:
    metadata:
      labels:
        app: dictionary
        rev: v1
    spec:
      containers:
      - name:            dictionary-v1
        image:           k8sland/dictionary-svc-go:0.0.2
        imagePullPolicy: IfNotPresent
        args:            ["/app/dictionary", "-d", "list1.txt"]
        resources:
          requests:
            cpu:    100m
            memory: 4Mi
          limits:
            cpu:    200m
            memory: 8Mi
        ports:
        - name:          http
          containerPort: 4000