kind:       Deployment
apiVersion: apps/v1
metadata:
  name: dictionary-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary
      rev: v1
  template:
    metadata:
      labels:
        app: dictionary
        rev: v1
    spec:
      containers:
      - name:            dictionary
        image:           k8sland/dictionary-svc-go:0.0.2
        imagePullPolicy: IfNotPresent
        args:            ['/app/dictionary', '-a', '/var/dictionary/words', '-d', 'trump.txt']
        resources:
          requests:
            cpu:    100m
            memory: 4Mi
          limits:
            cpu:    200m
            memory: 8Mi
        ports:
        - name:          http
          containerPort: 4000
        volumeMounts:
        - name:      dictionary
          mountPath: /var/dictionary
      initContainers:
      - name:    git
        image:   luzhzh/git-client
        command: ['sh', '-c', 'rm -rf /var/dictionary/words && git clone https://github.com/k8sland/dictionaries.git /var/dictionary/words']
        volumeMounts:
        - name:      dictionary
          mountPath: /var/dictionary
      volumes:
      - name: dictionary
        hostPath:
          path: /home/docker/dictionary
