apiVersion: monitoring.coreos.com/v1
kind:       ServiceMonitor
metadata:
  name: hangman
  labels:
    app: hangman
spec:
  selector:
    matchLabels:
      app: hangman
  endpoints:
  - port: http
---
# Figure out which service monitor needs to be included
apiVersion: monitoring.coreos.com/v1
kind:       Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      app: hangman
  resources:
    requests:
      memory: 400Mi
---
# Expose Dashboard
apiVersion: v1
kind:       Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name:       web
    nodePort:   30900
    port:       9090
    protocol:   TCP
    targetPort: web
  selector:
    prometheus: prometheus