
---
# Deployment
apiVersion: apps/v1
kind:       Deployment
metadata:
  name: iconoflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iconoflix
  template:
    metadata:
      labels:
        app: iconoflix
    spec:
      containers:
      - name:  iconoflix
        image: quay.io/imhotepio/iconoflix:mem
        resources:
          !!! CHANGE_ME !!!
        ports:
        - containerPort: 4000
---
# Service
kind: Service
apiVersion: v1
metadata:
  name: iconoflix
spec:
  type:  NodePort
  selector:
    app: iconoflix
  ports:
  - port:     4000
    nodePort: 30400
