apiVersion: apps/v1
kind:       Deployment
metadata:
  name: fred
  labels:
    app: Grim-Reaper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fred
  template:
    metadata:
      labels:
        app: fred
    spec:
      containers:
      - name:            nginx
        image:           nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name:          http
          protocol:      TCP
          containerPort: 80