apiVersion: apiextensions.k8s.io/v1beta1
kind:       CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: painters.workload.k8sland.io
spec:
  group: workload.k8sland.io
  names:
    kind:   Painter
    plural: painters
    shortNames:
      - pa
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            color:
              enum:
              - Red
              - Blue
              - Green
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
