apiVersion: networking.istio.io/v1alpha3
kind:       VirtualService
metadata:
  name: routes
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: hangman
        port:
          number: 5000